### ISSUE TITLE
Test: Verify via querying the database whether a new row is present in the database for that user with correct details. 

### ISSUE THREAD

**Issue by LoukikNaik** [CSE-210/Exercise-Buddy-App#81]

**Comment by cknguyen123** [comment]
Unsure what is meant by new row since default fields are set during create account activity. New data is then placed into those fields during  Preference Activity. Testing is covered with the preference Page UI test  and Back button test where it uses actual firestore db. It updates the db as well and the new data is grabbed and displayed
